Feature/xml descriptions
Henningson/FeatureIDETeam2 pull request #19
Opened 2017-09-26 14:04 UTC by DawidSA2017

This is Story Card 1

2017-09-26 15:20 UTC, tthuem requested changes
I had a look already, but seems there are numerous changes necessary. Please revise and start new review request.

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/base/impl/AConstraint.java
> +
Is this import really necessary?

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +import guidsl.node;
There should be no need to use Nodes from GUIDSL here.

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +		// Team1 Story1
Please avoid such comments, does not help as there is a story 1 in team 1 every year.

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +							- 1);
This line is not clear to me.

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +					// Story1
as above

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +
Why only empty lines here?

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelWriter.java
> +			//createXmlConstraintDescription(doc, object.getConstraints().get(i), rule);
Do not add code in comments. Remove?

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelWriter.java
> +//				+ "\n");
as above

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelWriter.java
> +		descr.setTextContent("Das ist ein Test");
German

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/localization/StringTable.java
> +		"Renaming feature ";
Why are all these added here?

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/actions/ChangeConstraintDescriptionAction.java
> +		//TODO Team1 Story2 rename dialog
as above

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/actions/ChangeConstraintDescriptionAction.java
> +				description.trim();
Why are you using the old formatter? Did you update to all recent commits from develop before formatting?

2017-09-26 15:20 UTC, tthuem commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/actions/CreateConstraintWithAction.java
> +
Looks like the formatter was not applied here.

2017-09-26 15:20 UTC, tthuem commented on tests/de.ovgu.featureide.fm.core-test/src/de/ovgu/featureide/fm/core/io/TAbstractFeatureModelReaderWriter.java
> +
Why changed?

2017-09-26 15:20 UTC, tthuem commented on tests/de.ovgu.featureide.fm.core-test/src/de/ovgu/featureide/fm/core/io/xml/TXmlFeatureModelFormat.java
> +		// newFm.addConstraint(c3);
Numerous lines with code in comments here.

2017-09-26 15:20 UTC, tthuem commented on tests/de.ovgu.featureide.fm.core-test/src/testFeatureModels/.featureide/constrainDescriptionWriteTwoRulesTest.xml.xml/constrainDescriptionWriteTwoRulesTest.xml.xml.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Why added something from .featureide folder? Should not be necessary, right?

2017-09-26 15:20 UTC, tthuem commented on tests/de.ovgu.featureide.fm.core-test/src/testFeatureModels/constraintDescriptionTwoRulesTest.xml
> +				Test Description
I would use different descriptions to alse check that descriptions are not messed up. And maybe also a third rule without any description.

2017-09-27 07:51 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/base/impl/AConstraint.java
> +
Yes, we are using it in the setDescription Method to check that the description parameter is not null.

2017-09-27 07:52 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +import guidsl.node;
okay, removed.

2017-09-27 07:58 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +		// Team1 Story1
removed all

2017-09-27 08:10 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +							- 1);
Checked the meaning of the line and removed it after realizing that it makes no sense there.

2017-09-27 08:10 UTC, merged

2017-09-27 08:54 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +
In this line the DESCRIPTION is suppose to be ignored. So the method should return without adding any nodes, just return the current list. The actual readout of the description happens at a different point.

2017-09-27 09:00 UTC, Henningson commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/base/impl/AConstraint.java
> +		this.description =
Format

2017-09-27 09:05 UTC, Henningson commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/localization/StringTable.java
> +  public static final String CONSTRAINT_DESCRIPTION = "Constraint Description";
Indent line 458 and 462

2017-09-27 09:06 UTC, Henningson commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/localization/StringTable.java
> +  public static final String PLEASE_ENTER_A_DESCRIPTION_FOR_CONSTRAINT_ = "Please enter a description for constraint '";
As above

2017-09-27 09:07 UTC, Henningson commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/FeatureDiagramEditor.java
> +    changeConstraintDescriptionAction =	new ChangeConstraintDescriptionAction(this, featureModel, null);
As above

2017-09-27 09:09 UTC, Henningson commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/FeatureDiagramEditor.java
> +		} else if (editConstraintAction.isEnabled()	&& !connectionSelected) {
Remove the tab stop before &&

2017-09-27 09:11 UTC, Henningson commented on plugins/de.ovgu.featureide.fm.ui/src/de/ovgu/featureide/fm/ui/editors/featuremodel/actions/DeleteAllAction.java
> +		setEnabled(!feature.getStructure().isRoot()	&& feature.getStructure().hasChildren());
As above

2017-09-27 09:13 UTC, Henningson commented on tests/de.ovgu.featureide.fm.core-test/src/de/ovgu/featureide/fm/core/io/xml/TXmlFeatureModelFormat.java
> +		String constraindescriptionFromXml =
Change constraindescriptionFromXml to constraintDescriptionFromXml

2017-09-27 09:21 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelWriter.java
> +			//createXmlConstraintDescription(doc, object.getConstraints().get(i), rule);
removed

2017-09-27 09:21 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelWriter.java
> +//				+ "\n");
removed

2017-09-27 09:21 UTC, DawidSA2017 commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelWriter.java
> +		descr.setTextContent("Das ist ein Test");
removed